# -*- coding: utf-8 -*-
"""mymodule.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MPRbEArfs7E3ldnLsxkco3XHFe6oCv-w
"""

def greeting(name):
  print("Hello, " + name)